# Generated by Django 5.2.8 on 2025-11-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormProcessingStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='global', max_length=64, unique=True)),
                ('sorted_count', models.PositiveIntegerField(default=0)),
                ('unsorted_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Form Processing Stat',
                'verbose_name_plural': 'Form Processing Stats',
            },
        ),
    ]
