# Generated by Django 5.2.7 on 2025-10-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer_extraction_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracteddata',
            name='summary_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
