# Generated by Django 5.2.7 on 2025-10-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer_extraction_app', '0002_extracteddata_summary_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extracteddata',
            name='summary_text',
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='summary_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
