# Generated by Django 5.2.7 on 2025-11-12 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer_extraction_app', '0005_emailtracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtracking',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_tracking', to='organizer_extraction_app.taxdocument'),
        ),
    ]
