# Generated by Django 5.2.7 on 2025-11-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer_extraction_app', '0007_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('tax_preparer', 'Tax Preparer')], default='client', max_length=20),
        ),
    ]
