# Generated by Django 5.2.7 on 2025-11-13 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer_extraction_app', '0008_alter_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cchid', models.CharField(editable=False, max_length=20, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('document_upload', 'Document Upload'), ('email_sent', 'Email Sent'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('document_downloaded', 'Document Downloaded')], max_length=50)),
                ('description', models.TextField()),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='organizer_extraction_app.taxdocument')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['document', '-timestamp'], name='organizer_e_documen_d78fa5_idx'), models.Index(fields=['user', '-timestamp'], name='organizer_e_user_id_780d04_idx'), models.Index(fields=['cchid'], name='organizer_e_cchid_6683c0_idx')],
            },
        ),
    ]
