# Generated by Django 5.2.7 on 2025-11-13 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer_extraction_app', '0009_activitylog'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='activitylog',
            name='organizer_e_cchid_6683c0_idx',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='cchid',
        ),
    ]
