# Generated by Django 5.2.8 on 2025-11-14 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer_extraction_app', '0010_add_email_automation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxdocument',
            name='form_detection_enabled',
        ),
        migrations.RemoveField(
            model_name='taxdocument',
            name='organizer_folder',
        ),
        migrations.RemoveField(
            model_name='taxdocument',
            name='processed_files_hash',
        ),
    ]
