# Generated by Django 5.2.8 on 2025-11-14 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer_extraction_app', '0010_remove_activitylog_organizer_e_cchid_6683c0_idx_and_more'),
        ('organizer_extraction_app', '0011_remove_taxdocument_form_detection_enabled_and_more'),
    ]

    operations = [
    ]
