# Generated by Django 5.2.8 on 2025-11-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer_extraction_app', '0012_merge_20251114_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFProcessingToggle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('document_upload', 'Document Upload'), ('email_sent', 'Email Sent'), ('document_downloaded', 'Document Downloaded')], max_length=50),
        ),
        migrations.CreateModel(
            name='OrganizerFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('folder_path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('client_name',)},
            },
        ),
        migrations.CreateModel(
            name='ProcessedFileHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('file_hash', models.CharField(max_length=64)),
                ('file_name', models.CharField(max_length=255)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['client_name', 'file_hash'], name='organizer_e_client__ac7057_idx')],
                'unique_together': {('client_name', 'file_hash')},
            },
        ),
    ]
