# Generated by Django 5.2.8 on 2025-11-14 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer_extraction_app', '0012_merge_20251114_1030'),
        ('organizer_extraction_app', '0013_pdfprocessingtoggle_alter_activitylog_action_and_more'),
    ]

    operations = [
    ]
