# Generated by Django 5.2.8 on 2025-11-17 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer_extraction_app', '0014_merge_20251114_1315'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PDFProcessingToggle',
        ),
    ]
