# Generated by Django 5.2.8 on 2025-11-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer_extraction_app', '0015_delete_pdfprocessingtoggle'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracteddata',
            name='custom_fields',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
