# Generated by Django 5.2.8 on 2025-11-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer_extraction_app', '0016_extracteddata_custom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracteddata',
            name='sorted_forms_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='unsorted_forms_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
