# Generated by Django 5.2.8 on 2025-11-19 15:56

import organizer_extraction_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer_extraction_app', '0017_extracteddata_sorted_forms_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracteddata',
            name='classified_forms',
            field=models.JSONField(blank=True, default=organizer_extraction_app.models.default_classified_forms),
        ),
    ]
