# Generated by Django 5.2.8 on 2025-11-27 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer_extraction_app', '0002_add_completion_percentage'),
        ('organizer_extraction_app', '0021_foldermonitoring'),
    ]

    operations = [
    ]
