# Generated by Django 5.2.8 on 2025-11-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer_extraction_app', '0025_remove_classified_forms'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracteddata',
            name='logic',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
